user.name = "Felix Geller"
user.email = "fgeller@protonmail.com"
user.signingkey = "71E54A69B0C4269F"

revset-aliases."immutable_heads()" = "trunk() | tags()"

ui.default-command = ["log", "-r", "bookmarks()", "--limit", "10"]
ui.diff.tool = ["difft", "--color=always", "$left", "$right"]
ui.paginate = "auto"
