user.name = "Felix Geller"
user.email = "fgeller@protonmail.com"

signing.key = "71E54A69B0C4269F"
signing.behavior = "own"
signing.backend = "gpg"

revset-aliases."immutable_heads()" = "trunk()"

ui.default-command = ["log", "-r", "ancestors(bookmarks(), 3) | bookmarks() | @ | ancestors(@, 3) | descendants(@) | descendants(bookmarks()) ~ remote_bookmarks()", "--limit", "20"]
ui.diff-formatter = ["difft", "--color=always", "$left", "$right"]
ui.paginate = "auto"
ui.conflict-marker-style = "git"

git.private-commits = "description(glob:'wip:*') | description(glob:'private:*')"
