
[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 1, y = 1 }
dynamic_padding = true
option_as_alt = "Both"

[font]
size = 11.25

[font.normal]
family = "JetBrainsMono Nerd Font"

[selection]
save_to_clipboard = true

[general]

live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-latte.toml"
]

[terminal]
